routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CastController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'] );
Route::get('/form', [AuthController::class, 'register'] );
Route::post('/register', [AuthController::class, 'welcome'] );
Route::get('master', function(){
    return view('adminlte/master');
} );

Route::get('table', function(){
    return view('items/index');
} );
Route::get('data-tables', function(){
    return view('items/data_tabel');
} );

// Route::get('/cast', [CastController::class, 'index'] );
// Route::get('/cast/create', [CastController::class, 'create'] );
// Route::post('/cast', [CastController::class, 'store'] );
// Route::get('/cast/{cast_id}', [CastController::class, 'show'] );
// Route::get('/cast/{cast_id}/edit', [CastController::class, 'edit'] );
// Route::put('/cast/{cast_id}', [CastController::class, 'update'] );
// Route::delete('/cast/{cast_id}', [CastController::class, 'destroy'] );

Route::resource('cast', CastController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/pemeran.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class pemeran extends Model
{
    protected $table="cast";
    protected $fillable = ["name","umur","bio"];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function register(){
        return view('form');
    }
    public function welcome(Request $request){
        //dd($request->all());
        return view('welcome',[
            "fname" => $request['fname'],
            'lname' => $request['lname'],
            'jenis' => $request['nationality']
        ]);
    }
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\pemeran;

class CastController extends Controller
{
    //---------Index-----------------
    public function index(){
        //$list = DB::table('cast')->get();
        $list = pemeran::all();
        return view('post/index', compact('list'));
    }
    //---------Create-----------------
    public function create(){
        return view('post/create');
    }
    //---------Store-----------------
    public function store(Request $request){
        $pemeran = new pemeran;

        $request->validate([
            'name' => 'required',
            'umur' => 'required',
            'bio' => 'required',
        ]);
        /*$query = DB::table("cast")->insert([
            "name" => $request['name'],
            "umur" => $request['umur'],
            "bio" => $request['bio']
        ]);

        $pemeran = new pemeran;
        $pemeran->name = $request["name"];
        $pemeran->umur = $request["umur"];
        $pemeran->bio = $request["bio"];
        $pemeran->save();*/

        $pemeran = pemeran::create([
            "name" => $request['name'],
            "umur" => $request['umur'],
            "bio" => $request['bio']
        ]);

        return redirect('cast')->with('success', 'Data Berhasil Ditambahkan!');
    }
    //---------Show-----------------
    public function show($cast_id){
        //$cast = DB::table('cast')->where('id',$cast_id)->first();
        $cast = pemeran::find($cast_id);
        return view('post/show',compact('cast'));
    }
    //---------Edit-----------------
    public function edit($cast_id){
        //$cast = DB::table('cast')->where('id',$cast_id)->first();
        $cast = pemeran::find($cast_id);
        return view('post/edit',compact('cast'));
    }
    //---------Update-----------------
    public function update($cast_id, Request $request){
        $request->validate([
            'name' => 'required',
            'umur' => 'required',
            'bio' => 'required',
        ]);
        /*$update = DB::table('cast')
        ->where('id',$cast_id)
        ->update([
            "name" => $request['name'],
            "umur" => $request['umur'],
            "bio" => $request['bio']
        ]);*/
        $cast = pemeran::where("id",$cast_id)
        ->update([
            "name" => $request['name'],
            "umur" => $request['umur'],
            "bio" => $request['bio']
        ]);


        return redirect('cast')->with('success', 'Data Berhasil Diubah!');
    }
    //---------Destroy-----------------
    public function destroy($cast_id){
        /*$delete = DB::table('cast')
        ->where('id',$cast_id)
        ->delete();*/
        $delete=pemeran::destroy($cast_id);
        return redirect('cast')->with('success', 'Data Berhasil Dihapus!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('index');
    }
}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Blank Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('adminlte.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('adminlte.partials.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @yield('content')
 </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('adminlte/dist/js/demo.js') }}"></script>
@stack('script')
<script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
</body>
</html>

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('adminlte/dist/img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('adminlte/dist/img/user8-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('adminlte/dist/img/user3-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Buat Account Baru</h1>
    <h2>Sign Up Form</h2>
    <form action="/register" method="POST">
        @csrf
        <label for="fname">First name:</label><br><br>
        <input type="text" id="fname" name="fname"><br><br>
        <label for="lname">Last name:</label><br><br>
        <input type="text" id="lname" name="lname"><br><br>

        <label for="nationality">Nationality:</label>
        <br><br>
        <select id="nationality" name="nationality">
            <option value="indonesia">Indonesia</option>
            <option value="malaysia">Malaysia</option>
            <option value="singapore">Singapore</option>
            <option value="vietnam">Vietnam</option>
        </select>
        <br><br>

        <label for="gender">Gender:</label><br><br>
        <input type="radio" id="male" name="gender" value="male">
        <label for="male">Male</label><br>
        <input type="radio" id="female" name="gender" value="female">
        <label for="female">Female</label><br>
        <input type="radio" id="other" name="gender" value="other">
        <label for="other">Other</label><br><br>

        <label for="language">Language Spoken:</label><br><br>
        <input type="checkbox" id="indonesia" name="language" value="indonesia">
        <label for="indonesia">Bahasa Indonesia</label><br>
        <input type="checkbox" id="english" name="language" value="english">
        <label for="english">English</label><br>
        <input type="checkbox" id="other" name="language" value="other">
        <label for="other">Other</label><br><br>

        <label for="bio">Bio:</label><br><br>
        <textarea name="bio" rows="10" cols="30">
        </textarea>
        <br><br>
        <input type="submit" value="Signup">

      </form>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SanberBook</title>
</head>
<body>
    <h1>SanberBook</h1>
    <h2>Social Media Developer Santai Berkualitas</h2>
    <p>Belajar dan Berbagi agar hidup ini semakin santai berkualitas</p>
    <h2>Benefit Join di SanberBook</h2>
<ul>
  <li>Mendapatan motivasi dari sesama developer</li>
  <li>Sharing knowledge dari para mastah Sanber</li>
  <li>Dibuat oleh calon web developer terbaik</li>
</ul>  

<h2>Cara Bergabung ke SanberBook</h2>

<ol>
  <li>Mengunjungi Website ini</li>
  <li>Mendaftar di <a href="/form">Form Sign Up</a></li>
  <li>Selesai</li>
</ol> 
</body>
</html>

resources/views/items/index.blade.php
@extends('adminlte.master')

@section('content')
<table class="table table-bordered">
    <thead>                  
      <tr>
        <th style="width: 10px">#</th>
        <th>Task</th>
        <th>Progress</th>
        <th style="width: 40px">Label</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1.</td>
        <td>Update software</td>
        <td>
          <div class="progress progress-xs">
            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
          </div>
        </td>
        <td><span class="badge bg-danger">55%</span></td>
      </tr>
      <tr>
        <td>2.</td>
        <td>Clean database</td>
        <td>
          <div class="progress progress-xs">
            <div class="progress-bar bg-warning" style="width: 70%"></div>
          </div>
        </td>
        <td><span class="badge bg-warning">70%</span></td>
      </tr>
      <tr>
        <td>3.</td>
        <td>Cron job running</td>
        <td>
          <div class="progress progress-xs progress-striped active">
            <div class="progress-bar bg-primary" style="width: 30%"></div>
          </div>
        </td>
        <td><span class="badge bg-primary">30%</span></td>
      </tr>
      <tr>
        <td>4.</td>
        <td>Fix and squish bugs</td>
        <td>
          <div class="progress progress-xs progress-striped active">
            <div class="progress-bar bg-success" style="width: 90%"></div>
          </div>
        </td>
        <td><span class="badge bg-success">90%</span></td>
      </tr>
    </tbody>
  </table>
   
@endsection

resources/views/post/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Add New Cast</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/cast" method="POST">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="name">Name :</label>
          <input type="text" class="form-control" name="name" id="name" placeholder="Enter name">
        </div>
        @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="umur">Umur :</label>
          <input type="text" class="form-control" name="umur" id="umur" placeholder="Enter age">
        </div>
        @error('umur')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="bio">Bio :</label>
          <textarea class="form-control" rows="5" name="bio" id="bio" placeholder="Bio"></textarea>
        </div>
        @error('bio')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
      </div>
    </form>
  </div>
   
@endsection

resources/views/post/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Edit Cast {{ old('id', $cast->id) }}</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="/cast/{{$cast->id}}" method="POST">
      @csrf
      @method('PUT')
      <div class="card-body">
        <div class="form-group">
          <label for="name">Name :</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name', $cast->name) }}" placeholder="Enter name">
        </div>
        @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="umur">Umur :</label>
          <input type="text" class="form-control" name="umur" id="umur" value="{{ old('umur', $cast->umur) }}"placeholder="Enter age">
        </div>
        @error('umur')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="bio">Bio :</label>
          <textarea class="form-control" rows="5" name="bio" id="bio" placeholder="Bio">{{ old('bio', $cast->bio) }}</textarea>
        </div>
        @error('bio')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
      </div>
    </form>
  </div>
   
@endsection

resources/views/post/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="card m-3">
    <div class="card-header">
      <h3 class="card-title">Cast List</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif

        <a class="btn btn-primary mb-2" href="{{ route('cast.create') }}">Add New Cast</a>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">No</th>
            <th>Name</th>
            <th>Umur</th>
            <th>Bio</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($list as $key => $item)
              <tr>
                  <td>{{  $key + 1 }}</td>
                  <td>{{  $item->name }}</td>
                  <td>{{  $item->umur }}</td>
                  <td>{{  $item->bio }}</td>
                  <td style="display: flex;">
                    <a class="btn btn-primary btn-sm ml-2" href="{{ route('cast.show',['cast'=>$item->id]) }}">Detail</a>
                    <a class="btn btn-primary btn-sm ml-2" href="/cast/{{ $item->id }}/edit">Edit</a>
                    <form action="/cast/{{ $item->id }}" method="post">
                    @csrf
                    @method('delete')
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm ml-2">
                    </form>
                  </td>
              </tr>

              @empty
            <tr>
                <td colspan="4" align="center"> No Data</td>
            </tr>
              
          @endforelse
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->

  </div>
   
@endsection

resources/views/post/show.blade.php
@extends('adminlte.master')
@section('content')
<div class="mt-3 ml-3">
    <h4>{{ $cast->name }}</h4>
    <h2>{{ $cast->umur }}</h2>
</div>
    
@endsection